RESIZE_IMAGE_WIDTH = 1200
EDGE_DETECTION_LOW_THRESHOLD = 120
EDGE_DETECTION_HIGH_THRESHOLD = 300 
EDGE_DETECTION_APERTURE = 3

LINE_DETECTION_THRESHOLD = 100
LINE_DETECTION_DIAGONAL_LINE_ELIMINATION = True
LINE_DETECTION_DIAGONAL_LINE_ELIMINATION_THRESHOLD_DEGREES = 30

MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE = .5

RANSAC_OFFSET_TOLERANCE = .15
RANSAC_BEST_SOLUTION_TOLERANCE = .1

BORDER_REFINEMENT_NUM_SURROUNDING_SQUARES_IN_WARPED_IMG = 5
BORDER_REFINEMENT_WARPED_SQUARE_SIZE = [50, 50]
BORDER_REFINEMENT_SOBEL_KERNEL_SIZE = 3
BORDER_REFINEMENT_LINE_WIDTH = 4