DATASET:
  PATH: data/pieces
  WORKERS: 2
  CLASSES:
    - black_bishop
    - black_king
    - black_knight
    - black_pawn
    - black_queen
    - black_rook
    - white_bishop
    - white_king
    - white_knight
    - white_pawn
    - white_queen
    - white_rook
  BATCH_SIZE: 16
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE: [100, 200]
    RANDOM_HORIZONTAL_FLIP: null
    COLOR_JITTER:
      BRIGHTNESS: 0.
      CONTRAST: 0.
      SATURATION: 0.
      HUE: 0.
    SHEAR: null
    SCALE:
      VERTICAL: null
      HORIZONTAL: null
    TRANSLATE:
      VERTICAL: null
      HORIZONTAL: null
TRAINING:
  MODEL:
    REGISTRY: PIECE_CLASSIFIER
    NAME: CNN100_3Conv_3Pool_3FC
  PHASES:
    - PARAMS: all
      EPOCHS: 6
      OPTIMIZER:
        LEARNING_RATE: 0.0001
        NAME: Adam
